# Generated by Django 4.1.2 on 2022-10-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_detail_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail',
        ),
    ]
